In [ ]:
a = numpy.array([1,2,3])
print(b)

import numpy as np

In [ ]:
# 1. list, tuple을 통한 array (배열) 생성
a = [12, 13, 14]
b = (2, 5, 1)

arr1 = np.array(a)
arr2 = np.array(b)

print(a) # list와 tuple은 요소간 , 가 있다
print(b)
print(arr1) # array는 콤마가 없다
print(arr2)

[12, 13, 14]
(2, 5, 1)
[12 13 14]
[2 5 1]


In [ ]:
a = np.array([12, 13, 14])
print(a)

[12 13 14]


In [ ]:
b = np.array([[1,2,3],[2,3,4]])
print(b)
print(a)

[[1 2 3]
 [2 3 4]]
[12 13 14]


#### numpy에서 자주 사용하는 메서드

##### 1.배열 정보: .shape, .ndim, .dtype, .size
##### 2.배열 변형: .reshape(), .ravel(), .flatten(), .T, .astype(), .squeeze()
##### 3.수학 연산: .sum(), .mean(), .std(), .var(), .min(), .max(), .argmin(), .argmax(), .cumsum(), .cumprod()
##### 4.배열 조작: .concatenate(), .stack(), .hstack(), .vstack(), .split(), .hsplit(), .vsplit(), .unique()
##### 5.논리 연산: .where(), .any(), .all()
##### 6.난수 생성: np.random.rand(), np.random.randn(), np.random.randint(), np.random.shuffle()

### --------------------------------------------------------------------------------------------------------------------------------

#### 1.배열 정보: .shape, .ndim, .dtype, .size, .itmesize

###### .shape: 배열의 형태(차원의 크기)를 반환
###### .ndim: 배열의 차원(축 개수) 반환
###### .dtype: 배열의 데이터 타입(정수, 실수, 복소수, 문자열 등..) 확인
###### .size: 배열의 총 원소 개수 반환
###### .itemsize: 원소 하나의 크기(단위: byte)

In [ ]:
# array 생성1: numpy array로 1차원 벡터 생성

arr1 = np.array([0, 2, 2.4, 9])

print(arr1)
print('-'*30)

print(f'type is: {type(arr1)}') # type(자료형)은 파이썬에서 제공
print(f'shape is: {arr1.shape}')
print(f'ndim is: {arr1.ndim}')
print(f'dtype is: {arr1.dtype}')
print(f'size is: {arr1.size}')
print(f'itemsize is: {arr1.itemsize}')

[0.  2.  2.4 9. ]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (4,)
ndim is: 1
dtype is: float64
size is: 4
itemsize is: 8


In [ ]:
# array 생성2: numpy array로 2차원 배열 생성

# arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr2)
print('-'*30)

print(f'type is: {type(arr2)}')
print(f'shape is: {arr2.shape}')
print(f'ndim is: {arr2.ndim}')
print(f'dtype is: {arr2.dtype}')
print(f'size is: {arr2.size}')
print(f'itemsize is: {arr1.itemsize}')

[[1 2 3]
 [4 5 6]]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (2, 3)
ndim is: 2
dtype is: int32
size is: 6
itemsize is: 8


In [ ]:
# array 생성 3: zeros()로 array 생성

# a1과 a3를 비교하는게 중요
a1 = np.zeros(5)       # shape = (5,)
a2 = np.zeros((2,3))   # shape = (2,3)
a3 = np.zeros((1,5))   # shape = (1,5)

print(a1)
print('-'*30)
print(f'type is: {type(a1)}')
print(f'shape is: {a1.shape}')
print(f'ndim is: {a1.ndim}')
print(f'dtype is: {a1.dtype}')
print(f'size is: {a1.size}')
print(f'itemsize is: {a1.itemsize}')
print('='*30)

print(a2)
print('-'*30)
print(f'type is: {type(a2)}')
print(f'shape is: {a2.shape}')
print(f'ndim is: {a2.ndim}')
print(f'dtype is: {a2.dtype}')
print(f'size is: {a2.size}')
print(f'itemsize is: {a2.itemsize}')
print('='*30)

print(a3)
print('-'*30)
print(f'type is: {type(a3)}')
print(f'shape is: {a3.shape}')
print(f'ndim is: {a3.ndim}')
print(f'dtype is: {a3.dtype}')
print(f'size is: {a3.size}')
print(f'itemsize is: {a3.itemsize}')

[0. 0. 0. 0. 0.]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (5,)
ndim is: 1
dtype is: float64
size is: 5
itemsize is: 8
[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (2, 3)
ndim is: 2
dtype is: float64
size is: 6
itemsize is: 8
[[0. 0. 0. 0. 0.]]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (1, 5)
ndim is: 2
dtype is: float64
size is: 5
itemsize is: 8


In [ ]:
aa = np.zeros((3,1))
bb = np.zeros((1,3))
print(aa)
print(aa.shape)

print(bb)
print(bb.shape)

[[0.]
 [0.]
 [0.]]
(3, 1)
[[0. 0. 0.]]
(1, 3)


In [ ]:
a1 = np.zeros([2,3])
a2 = np.zeros(shape=[2,3])
a3 = np.zeros(shape=(2,3))
print(a1)
print(a2)
print(a3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.zeros(shape=(6,2))
print(arr)
print('='*30)

for i in range(6):
    arr[i] = (i,i) # arr[i]는 i번째 행

print(arr)
print(arr[2][1]) # arr의 2행 1열의 요소에 접근

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]
2.0


In [ ]:
# array 생성 4: ones()로 array 생성

a1 = np.ones(5)
a2 = np.ones((2, 3), dtype=np.int32)
a3 = np.ones((1,5), dtype=int)

print(a1)
print('-'*30)
print(f'type is: {type(a1)}')
print(f'shape is: {a1.shape}')
print(f'ndim is: {a1.ndim}')
print(f'dtype is: {a1.dtype}')
print(f'size is: {a1.size}')
print('='*30)

print(a2)
print('-'*30)
print(f'type is: {type(a2)}')
print(f'shape is: {a2.shape}')
print(f'ndim is: {a2.ndim}')
print(f'dtype is: {a2.dtype}')
print(f'size is: {a2.size}')
print('='*30)

print(a3)
print('-'*30)
print(f'type is: {type(a3)}')
print(f'shape is: {a3.shape}')
print(f'ndim is: {a3.ndim}')
print(f'dtype is: {a3.dtype}')
print(f'size is: {a3.size}')
print('='*30)

[1. 1. 1. 1. 1.]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (5,)
ndim is: 1
dtype is: float64
size is: 5
[[1 1 1]
 [1 1 1]]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (2, 3)
ndim is: 2
dtype is: int32
size is: 6
[[1 1 1 1 1]]
------------------------------
type is: <class 'numpy.ndarray'>
shape is: (1, 5)
ndim is: 2
dtype is: int32
size is: 5


In [ ]:
a = np.ones(5)
print(f'a is: {a}')
print(f'dtype of a is: {a.dtype}')
print('='*30)

# 참고:교재에는 int로 되어있는데, np.int32로 바꿈
b = np.ones(5, dtype=np.int32)
#b = np.ones(5, dtype=int) # 위와 같은 결과임
print(f'b is: {b}')
print(f'dtype of b is: {b.dtype}')

a is: [1. 1. 1. 1. 1.]
dtype of a is: float64
b is: [1 1 1 1 1]
dtype of b is: int32


In [ ]:
# array 생성 5: empty()로 array 생성

a = np.empty((2,2))
print(f'a is: \n{a}')
print(f'dtype of a is: {a.dtype}')
print('='*60)

b = np.empty(5, dtype=np.int32) # 32bit integer
print(f'b is: {b}')
print(f'dtype of b is: {b.dtype}')

a is: 
[[0.  2. ]
 [2.4 9. ]]
dtype of a is: float64
b is: [1 1 1 1 1]
dtype of b is: int32


In [ ]:
# 참고: random number와 empty 비교
a = np.random.rand(2,3)
print(a)

b = np.random.random((2,3))
print(b)

[[0.875124   0.46923076 0.97339353]
 [0.96668237 0.21117806 0.97642895]]
[[0.33117297 0.54960733 0.11124454]
 [0.04626475 0.48385392 0.23210212]]


In [ ]:
# array 생성 6: eye()=I(identity matrix)로 array 생성

a = np.eye(3, dtype=np.int32)
print(a)
print('='*20)

b = np.eye(3, k=1, dtype=np.int32)
print(b)
print('='*20)

c = np.eye(3, k=2, dtype=np.int32)
print(c)
print('='*20)

d = np.eye(3, k=-1, dtype=np.int32)
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [0 0 0]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [ ]:
# array 생성 7: linspace() 함수로 array 생성

a = np.linspace(2, 3, 5) # 2와 3 사이를 5등분
b = np.linspace(2, 3, num=5)
c = np.linspace(2.0, 3.0, 5)
d = np.linspace(2.0, 3.0, 5, endpoint=False)  # endpoint = False
e = np.linspace(2.0, 3.0, 5, retstep=True)        # retstep = True (return step)

print(a,'\n','='*40, '\n')
print(b,'\n','='*40, '\n')
print(c,'\n','='*40, '\n')
print(d,'\n','='*40, '\n')
print(e)

[2.   2.25 2.5  2.75 3.  ] 

[2.   2.25 2.5  2.75 3.  ] 

[2.   2.25 2.5  2.75 3.  ] 

[2.  2.2 2.4 2.6 2.8] 

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [ ]:
# array 생성 8: arange() 함수로 array 생성 1

# range vs. arange

a = range(5)
print(a)
print(f'type of a is: {type(a)}')
print('='*40)

b = list(range(5))
print(b)
print(f'type of b is: {type(b)}')
print('='*40)

c = np.arange(5)
print(c)
print(f'type of c is: {type(c)}')
print('='*40)

range(0, 5)
type of a is: <class 'range'>
[0, 1, 2, 3, 4]
type of b is: <class 'list'>
[0 1 2 3 4]
type of c is: <class 'numpy.ndarray'>


In [ ]:
# array 생성 8: arange() 함수로 array 생성 2

a = np.arange(5)
print(a)
print('='*40)

b = np.arange(3, 7)
print(b)
print('='*40)

c = np.arange(2,9,3)
print(c)
print('='*40)

[0 1 2 3 4]
[3 4 5 6]
[2 5 8]


In [ ]:
# array 생성 8:  arange() 함수로 array 생성 3

a = np.arange(5) # a = [0,1,2,3,4]
print(a)
print('='*40)

a[2] = 10        # a = [0,1,10,3,4]
print(a)
print('='*40)

a[3] = '10'      # a = [0,1,10,10,4]
print(a)
print('='*40)

a[4] = 'onezero' # a = [0,1,10,10,'onezero'] :에러발생
print(a)
print('='*40)

[0 1 2 3 4]
[ 0  1 10  3  4]
[ 0  1 10 10  4]


ValueError: invalid literal for int() with base 10: 'onezero'

In [ ]:
# array 생성 9: zeros_like(), ones_like(), empty_like()

a = np.array([[1,2,3],
              [4,5,6]])
print(a, a.shape)

b = np.random.randint(1,10,(2,3,4,5))
print(b)
print(b.shape)

c = np.zeros_like(b)
print(c)
print(c.shape)

d = np.ones_like(b)
e = np.empty_like(b)

[[1 2 3]
 [4 5 6]] (2, 3)
[[[[5 1 5 3 2]
   [2 6 4 1 8]
   [1 6 6 8 6]
   [6 1 7 2 6]]

  [[9 9 3 7 4]
   [7 9 6 7 7]
   [5 2 1 3 7]
   [3 3 1 2 6]]

  [[7 2 9 9 9]
   [6 5 1 7 5]
   [9 5 1 6 5]
   [6 1 4 3 8]]]


 [[[9 2 8 3 2]
   [1 7 5 1 7]
   [9 8 1 9 6]
   [8 3 7 2 2]]

  [[2 3 7 7 6]
   [1 6 4 6 3]
   [8 2 1 3 1]
   [8 6 5 8 1]]

  [[5 1 8 6 8]
   [2 6 1 1 5]
   [2 8 3 2 2]
   [5 2 9 1 1]]]]
(2, 3, 4, 5)
[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]
(2, 3, 4, 5)


In [ ]:
# array 생성 10: 특정값을 넣을 때

a = 255*np.ones((3,3))
print(a)

b = np.full((3,3), 255)
print(b)
print(b.shape)

[[255. 255. 255.]
 [255. 255. 255.]
 [255. 255. 255.]]
[[255 255 255]
 [255 255 255]
 [255 255 255]]
(3, 3)


### --------------------------------------------------------------------------------------------------------------------------------

#### 2.배열 변형: .reshape(), .ravel(), .flatten(), .T, .astype(), .squeeze()
###### .reshape(): 배열의 형태 변경
###### .ravel() or flatten(): 다차원 배열을 1차원으로 변환
###### .T: 전치(transpose) (행과 열을 바꿈)
###### .astype(): 데이터 타입 변환
###### .squeeze(): 차원이 1인 축을 제거

In [ ]:
# squeeze() 함수

a = np.ones((2,1,2,2))
print(a)
print(a.shape)

b = np.squeeze(a)
print(b)
print(b.shape)

c = np.ones((2,1,1,2))
d = np.squeeze(c)
print(d.shape)

[[[[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]]]
(2, 1, 2, 2)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
(2, 2, 2)
(2, 2)


In [ ]:
# reshape() 함수 사용

a = np.arange(12) # (12,) 1차원 벡터
print(a)
print(f'shape of a is {a.shape}', '\n', '-'*50)

b = np.arange(12).reshape(3,4) # (3,4) 2차원 행렬
print(b)
print(f'shape of b is {b.shape}', '\n', '-'*50)

c = np.arange(12).reshape(-1,4)
print(c)
print(f'shape of c is {c.shape}', '\n', '-'*50)

d = np.arange(12).reshape(3,-1)
print(d)
print(f'shape of d is {d.shape}', '\n', '-'*50)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape of a is (12,) 
 --------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of b is (3, 4) 
 --------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of c is (3, 4) 
 --------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of d is (3, 4) 
 --------------------------------------------------


In [ ]:
a = np.arange(10000000) #(천만,)
b = a.reshape(int(10000000/5),5)
print(b.shape)

c = a.reshape(-1,5)
print(c.shape)

(2000000, 5)
(2000000, 5)


In [ ]:
# reshape(-1) 함수, ravel(), flatten() 함수 사용

a = np.arange(12).reshape(3,4)
print(a)
print(f'shape of a is {a.shape}', '\n', '-'*50)

b = a.ravel()
print(b)
print(f'shape of b is {b.shape}', '\n', '-'*50)

c = a.flatten()
print(c)
print(f'shape of c is {c.shape}', '\n', '-'*50)

d = a.reshape(-1)
print(d)
print(f'shape of d is {d.shape}', '\n', '-'*50)

e = a.reshape(1,-1)
print(e)
print(f'shape of e is {e.shape}', '\n', '-'*50)

f = a.reshape(-1,1)
print(f)
print(f'shape of f is {f.shape}', '\n', '-'*50)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of a is (3, 4) 
 --------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape of b is (12,) 
 --------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape of c is (12,) 
 --------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape of d is (12,) 
 --------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
shape of e is (1, 12) 
 --------------------------------------------------
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
shape of f is (12, 1) 
 --------------------------------------------------


In [ ]:
# 3차원 배열: 면,깊이(depth) x 행 x 열

a = np.arange(24).reshape(2,3,4)
print(a)
print(f'shape of a is {a.shape}', '\n', '-'*50)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape of a is (2, 3, 4) 
 --------------------------------------------------


In [ ]:
# numpy는 for문 없이 연산 가능

a = [1, 2, 3]
b = [4, 5, 6]

c = []
for i in range(len(a)):
    tmp = a[i] + b[i]
    c.append(tmp)

print(c)

a1 = np.array(a)
b1 = np.array(b)
c1 = a1 + b1
print(c1)

[5, 7, 9]
[5 7 9]


In [ ]:
# numpy는 배열의 크기가 달라도 연산 가능
# 리스트는 에러 발생
a = [[1, 2, 3],[2, 3, 4],[4, 5, 6]]
b = [4, 5, 6]
'''
c = []
for i in range(len(a)):
    tmp = a[i] + b[i]
    c.append(tmp)

print(c)
'''

a1 = np.array(a)
b1 = np.array(b)
c1 = a1 + b1
print(c1)

[[ 5  7  9]
 [ 6  8 10]
 [ 8 10 12]]


In [ ]:
# ndarray 내부 메모리 구조 확인

arr_c = np.array([[1, 2, 3], [2, 3, 4]], order='C')
arr_f = np.array([[1, 2, 1], [3, 4, 4]], order='F')

print(f'datatype of arr_c is {arr_c.dtype}')
print(f'datatype of arr_f is {arr_f.dtype}')
print('='*50)

print(arr_c)
# (row_size x itemsize, itemsize) -> (16, 8)
print(f'itemsize of arr_c is {arr_c.itemsize}')
print(f'C 스타일 strides: {arr_c.strides}')
print('='*50)

print(arr_f)
# (itemsize, col_size x itemsize) -> (8, 16)
print(f'itemsize of arr_r is {arr_f.itemsize}')
print(f'Fortran 스타일 strides: {arr_f.strides}')


datatype of arr_c is int32
datatype of arr_f is int32
[[1 2 3]
 [2 3 4]]
itemsize of arr_c is 4
C 스타일 strides: (12, 4)
[[1 2 1]
 [3 4 4]]
itemsize of arr_r is 4
Fortran 스타일 strides: (4, 8)


In [ ]:
arr = np.array([[[0,  1,  2,  3],
                 [4,  5,  6,  7],
                 [8,  9, 10, 11]],
                [[12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])

print(f'array is:\n {arr}','\n')
print(f'type is: {type(arr)}','\n')
print(f'ndim(축의 개수) is: {arr.ndim}','\n')
print(f'shape is: {arr.shape}','\n')
print(f'size is: {arr.size}','\n')
print(f'dtype is: {arr.dtype}','\n')
print(f'itemsize(요소의 bytes) is: {arr.itemsize}','\n') # 책은 4바이트

# 3d는 (depth, 행, 열)
print(f'strides is: {arr.strides}')

array is:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

type is: <class 'numpy.ndarray'> 

ndim(축의 개수) is: 3 

shape is: (2, 3, 4) 

size is: 24 

dtype is: int64 

itemsize(요소의 bytes) is: 8 

strides is: (96, 32, 8)


### numpy.dtype의 적용  -------------------------------------------------------------------------------------------------

In [ ]:
import numpy as np

In [ ]:
print(np.dtype(np.int16))

int16


In [ ]:
# 1. 데이터 타입 및 크기

arr = np.array([1, 2, 3], dtype=np.int32)  # int32 타입의 배열
print(arr.dtype)      # int32
print(arr.itemsize)   # 각 원소가 4바이트(int32) 크기를 가짐

int32
4


In [ ]:
# 2. 바이트 순서 (endian)

arr1 = np.array([1, 2, 3], dtype='>i4')  # Big Endian 4-byte integer
print(arr1.dtype)  # >i4
print(arr1)

arr2 = np.array([1, 2, 3], dtype='<i4')  # Little Endian 4-byte integer
print(arr2.dtype)  # <i4
print(arr2)

print(arr.tobytes())   # Big Endian 바이트 출력
print(arr2.tobytes())  # Little Endian 바이트 출력

>i4
[1 2 3]
int32
[1 2 3]
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03'
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
