### 4월 11일

In [ ]:
import numpy as np

In [ ]:
# 고급 인덱싱 (1)

# 고급 인덱싱

arr = np.array([[1, 2], [3, 4], [5, 6]])

print(arr)
print('='*30)

print(arr[[0, 1, 2], [0, 1, 0]])   # arr[[행 인덱스], [열 인덱스]]


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [ ]:
# 고급 인덱싱 (2)

# 4x3 배열 객체에서 고급 인덱싱 사용

arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(arr), print('='*30)

rows = np.array([[0, 0], [3, 3]], dtype=np.intp)
columns = np.array([[0, 2], [0, 2]], dtype=np.intp)
print(arr[rows, columns])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [ ]:
## 기본 인덱싱 (basic indexing) vs. 고급 인덱싱 (advanced indexing) (1)

# 기본 인덱싱: 원본 배열도 변경

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr), print('='*30)

view = arr[:2, :2]  # 기본 인덱싱
print(view), print('='*30)  # [[1 2], [4 5]]

view[0, 0] = 100  # 변경
print(view), print('='*30)  # [[100 2], [4 5]]
print(arr)   # 원본 배열도 변경 [[100 2 3], [4 5 6], [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
## 기본 인덱싱 (basic indexing) vs. 고급 인덱싱 (advanced indexing) (2)

# 고급 인덱싱: 원본 배열은 그대로 유지

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_indexed = arr[[0, 1], [1, 2]]  # 정수 배열 인덱싱 -> 고급 인덱싱

print(arr_indexed) # [2 6]

arr_indexed[0] = 100  # 변경
print(arr_indexed) # [100 6]
print(arr)  # 원본 배열은 그대로 임 [[1 2 3], [4 5 6], [7 8 9]]

[2 6]
[100   6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
'''
v = arange(100)
w = [2 2 2 2 2 ... 2 2 2 ] 2가 100개
x = 2

v + x = 102 ... 102 100개 나옴
'''

In [ ]:
# 참고) 브로드캐스팅: 조건1 (스칼라 연산)

v = np.array([2, 2, 2])
w = np.array([1, 2, 3]) # shape = (3,)
alpha = 2  # 스칼라 shape = ()

# 일반적인 연산
print(f'v + w = {v + w}')   # 벡터 + 벡터
print(f'v - w = {v - w}')   # 벡터 - 벡터
print(f'v * w = {v * w}')   # 벡터 * 벡터
print(f'w / v = {w / v}')   # 벡터 / 벡터
print('-'*20)

# 브로드캐스팅
print(f'alpha + w = {alpha + w}')   # 스칼라 + 행렬
print(f'alpha - w = {alpha - w}')   # 스칼라 - 행렬
print(f'alpha * w = {alpha * w}')   # 스칼라 - 행렬
print(f'w / alpha = {w / alpha}')   # 스칼라 - 행렬

v + w = [3 4 5]
v - w = [ 1  0 -1]
v * w = [2 4 6]
w / v = [0.5 1.  1.5]
--------------------
alpha + w = [3 4 5]
alpha - w = [ 1  0 -1]
alpha * w = [2 4 6]
w / alpha = [0.5 1.  1.5]


In [ ]:
# 참고) 브로드캐스팅: 조건2 (벡터와 행렬 연산)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # (2, 3)
arr2 = np.array([10, 20, 30])             # (3,)
    # [10 20 30] -> [[10 20 30]]  ((3,)이 (1,3)으로 자동 확장)

result = arr1 + arr2  # (2, 3) + (1, 3) -> (2, 3)
    # arr2의 (1,3)이 (2,3)으로 변환된 후, 연산 수행

print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
# 참고) 브로드캐스팅: 조건2 (벡터와 행렬 연산)

a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])  # (4,3)
b = np.array([0, 1, 2])       # (3,) -> (1,3) -> (4,3)
c = a + b

print(a.shape, b.shape, c.shape)
print(c)


(4, 3) (3,) (4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
# 참고) 브로드캐스팅 3-1: 차원이 다른 행렬 간 브로드캐스팅

arr1 = np.array([[1], [2], [3]])  # (3,1)
arr2 = np.array([10, 20, 30])     # (3,)
            # [10 20 30] -> [[10 20 30]]  ((3,)이 (1,3)으로 자동 확장)

result = arr1 + arr2  # (3,1) + (1,3) → (3,3)

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 참고) 브로드캐스팅 3-2: 차원이 다른 행렬 간 브로드캐스팅

arr1 = np.random.randint(0, 10, (3, 1, 4))  # (3, 1, 4)
arr2 = np.random.randint(0, 10, (1, 2, 4))  # (1, 2, 4)

result = arr1 + arr2

print(result.shape)  # (3, 2, 4)
print(result)

(3, 2, 4)
[[[13  6  9  9]
  [ 9 11  6  4]]

 [[17 12 13 10]
  [13 17 10  5]]

 [[13  8 16  7]
  [ 9 13 13  2]]]


In [ ]:
# 참고) 브로드캐스팅 4: 실패 사례

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3     (2,3)    (2,3)
arr2 = np.array([10, 20])               # (2,) -> (1,2) -> (2,2)
            # [10 20] -> [[10 20]]  ((2,)이 (1,2)으로 자동 확장)

print(arr1 + arr2)  # 마지막 차원이 다르므로 브로드캐스팅 불가능!

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
# 브로드캐스팅 규칙의 적용

arr1 = np.arange(4)
arr2 = arr1.reshape(4, 1)
arr3 = np.ones(5)
arr4 = np.ones((3, 4))

print(f'arr1 shape: {arr1.shape}')
print(f'arr2 shape: {arr2.shape}')
print(f'arr3 shape: {arr3.shape}')
print(f'arr4 shape: {arr4.shape}')
print('-'*30)

print(f'arr1 + arr2: \n{arr1 + arr2}')
print(f'(arr1 + arr2).shape : {(arr1+arr2).shape}')
print('-'*30)

print(f'arr2 + arr3: \n{arr2 + arr3}')
print(f'(arr2 + arr3).shape : {(arr2+arr3).shape}')
print('-'*30)

print(f'arr1 + arr4: \n{arr1 + arr4}')
print(f'(arr1 + arr4).shape : {(arr1+arr4).shape}')


arr1 shape: (4,)
arr2 shape: (4, 1)
arr3 shape: (5,)
arr4 shape: (3, 4)
------------------------------
arr1 + arr2: 
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
(arr1 + arr2).shape : (4, 4)
------------------------------
arr2 + arr3: 
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(arr2 + arr3).shape : (4, 5)
------------------------------
arr1 + arr4: 
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
(arr1 + arr4).shape : (3, 4)
------------------------------


In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (1)

# 행렬과 행렬의 행렬곱
# A.shape: (..., m, n)
# B.shape: (..., n, k)
# A@B shape: (..., m, k)
# 앞부분(...)은 브로드캐스팅 규칙을 따름
# 마지막 두 축을 유심히 보자 !!!

# 2D x 2D
A = np.random.randn(3, 4) # (3, 4)
B = np.random.randn(4, 5) # (4, 5)
C = A@B
print(C.shape)  # shape = (3, 5)
print(C)

# ----------------------------------#
D = np.random.randn(3, 4) # (3,4)
E = np.random.randn(3, 4) # (3,4)
F = D@E
print(F.shape)  # 실행 불가
print(F)

(3, 5)
[[-0.16383578  1.3296262   2.16888122 -1.1692853   0.69852644]
 [ 0.06469208 -0.13174202 -1.40494402 -0.31559151 -0.10909433]
 [ 1.16437893 -0.9603978   2.06007737 -1.4971195  -0.41434194]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (2)

# 행렬과 행렬의 행렬곱

# 3D × 2D (배치 행렬곱)
A = np.random.randn(10, 3, 4)
B = np.random.randn(4, 5) # (4,5) -> (1,4,5) -> (10,4,5)
C = A@B
print(C.shape)  # shape = (10, 3, 5)

# B행렬에서 batch에 해당하는 부분이 없는데,
# 그 부분이 브로드캐스팅으로 10이 되어, (10,4,5)가 됨

# 3D × 3D (브로드캐스트 + 행렬곱)
D = np.random.randn(2, 3, 4)
E = np.random.randn(1, 4, 5)
F = D@E
print(F.shape)  # shape = (2, 3, 5)


(10, 3, 5)
(2, 3, 5)


In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (3)

# 행렬과 행렬의 행렬곱 (실패사례)

# 3D × 2D (배치 행렬곱)
A = np.random.randn(10, 3, 4)
B = np.random.randn(2, 4, 5)
C = A@B   # 면(depth)의 크기가 달라서 행렬곱이 불가능
print(C.shape)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (10,3,4)->(10,newaxis,newaxis) (2,4,5)->(2,newaxis,newaxis)  and requested shape (3,5)

In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (4)

# 행렬과 벡터의 행렬곱
# 중요1) (m,) @ (m,n) -> 결과 (n,) : (m,)은 행 벡터로 간주
#    -> (1,m) @ (m,n) -> (1,n)이 아니고 (n,)
# 중요2) (m,n) @ (n,) -> 결과 (m,) : (n,)은 열 벡터로 간주
#    -> (m,n) @ (n,1) -> (m,1)이 아니고 (m,)
# 중요3) 행렬곱에서 (m,)은 행/열 개념이 명확하지 않음
#         -> .reshape()으로 명확하게 차원을 지정하는 것을 추천
#            or 뒤에서 배울 np.newaxis을 이용하는 것도 좋음

a = np.array([1, 2])       # shape (2,)
b = np.array([[3, 4],
              [5, 6]])     # shape (2, 2)

c = a @ b  # a -> (1,2)처럼 다룸
d = b @ a  # a -> (2,1)처럼 다룸

print(c.shape, c)  # shape (2,), [13 16]
print(d.shape, d)  # shape (2,), [11 17]



(2,) [13 16]
(2,) [11 17]


In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (5)

# 행렬과 벡터의 행렬곱
# 중요1) (m,) @ (m,n) -> 결과 (n,) : (m,)은 행 벡터로 간주
# 중요2) (m,n) @ (n,) -> 결과 (m,) : (n,)은 열 벡터로 간주
# 중요3) 행렬곱에서 (m,)은 행/열 개념이 명확하지 않음
#         -> .reshape()으로 명확하게 차원을 지정하는 것을 추천
#            or 뒤에서 배울 np.newaxis을 이용하는 것도 좋음

# 실패사례 (1)
a = np.array([1, 2])         # shape (2,)
b = np.array([[3, 4],
              [5, 6],
              [7, 8]])       # shape (3, 2)

c = b @ a  # a -> (2,1) 처럼 다룸
print(c.shape, c)

# 실행 안됨
d = a @ b   # a -> (1,2)처럼 다룸 : (1,2)@(3,2)

(3,) [11 17 23]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# 브로드캐스팅: 행렬곱(@ or np.matmul() 사용) (6)

# 행렬과 벡터의 행렬곱
# 중요1) (m,) @ (m,n) -> 결과 (n,) : (m,)은 행 벡터로 간주
# 중요2) (m,n) @ (n,) -> 결과 (m,) : (n,)은 열 벡터로 간주
# 중요3) 행렬곱에서 (m,)은 행/열 개념이 명확하지 않음
#         -> .reshape()으로 명확하게 차원을 지정하는 것을 추천
#            or 뒤에서 배울 np.newaxis을 이용하는 것도 좋음

# 실패사례 (2)
x = np.array([2, 1])
y = x.reshape(-1,1)
print(x.shape)       # (2,)
print(y.shape)       # (2,1)

result1 = x @ y  # x -> (1,2): (1,2)@(2,1) => (1,)
print(result1.shape, result1)

result = y @ x  # x -> (2,1): (2,1)@(2,1) 실행안됨

(2,)
(2, 1)
(1,) [5]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [ ]:
# 고급 인덱싱 (3)

# numpy.newaxis

arr = np.array([1, 2, 3])
print(arr.shape)      # (3,) -> 1D 배열

arr_new = arr[:, np.newaxis]  # 열 벡터 (3,1)로 변환
print(arr_new.shape)  # (3,1)
print(arr_new)        # [[1], [2], [3]]
print('='*20)

arr_reshape = arr.reshape(-1,1)
print(arr_reshape.shape)
print('='*20)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)     # (2,3) -> 2D 배열
print('-'*20)

arr_new2 = arr2[np.newaxis, :, :]  # 첫 번째 축(면) 차원 추가
print(arr_new2.shape) # (1,2,3)
print('-'*20)

arr_new3 = arr2[:, np.newaxis, :]  # 두 번째 축(행) 차원 추가
print(arr_new3.shape) # (2,1,3)

(3,)
(3, 1)
[[1]
 [2]
 [3]]
(3, 1)
(2, 3)
--------------------
(1, 2, 3)
--------------------
(2, 1, 3)


In [ ]:
# np.newaxis는 값이 None으로 상수로 취급
# 만약 함수이면 np.newaxis() 이런식으로 다뤄야겠지만,
# 실제로는 그냥 np.newaxis로 다룸
np.newaxis is None

True

In [ ]:
# 고급 인덱싱 (4)

# numpy.newaxis

arr = np.arange(25).reshape(5, 5)
print(arr.shape)     # (5,5)

# 특별한 언급이 없으면, 기존 배열 앞에 차원이 하나 추가됨.
# 즉, axis=0에 새 축 생김.
arr_3d_0 = arr[np.newaxis] # axis=0축에 새 축을 만듦
print(arr_3d_0.shape)  # (1, 5, 5) 3차원 행렬

arr_3d_1 = arr[:, np.newaxis, :]
print(arr_3d_1.shape)  # (5, 1, 5) 3차원 행렬

arr_3d_2 = arr[:, :, np.newaxis]
print(arr_3d_2.shape)  # (5, 5, 1) 3차원 행렬
print('='*10)


arr = np.arange(10)
print(arr.shape)     # (10,)

arr_row = arr[np.newaxis, :]
print(arr_row.shape) # (1, 10)

arr_col = arr[:, np.newaxis]
print(arr_col.shape) # (10, 1)

(5, 5)
(1, 5, 5)
(5, 1, 5)
(5, 5, 1)
(10,)
(1, 10)
(10, 1)


In [ ]:
# 고급 인덱싱 (5)

# numpy.newaxis, 브로드캐스팅, 고급 인덱싱

arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9,10,11]])  # (4,3)
print(arr), print('-'*20)

rows = np.array([0, 3], dtype=np.intp)    # shape=(2,)
columns = np.array([0, 2], dtype=np.intp) # shape=(2,)
a = arr[rows, columns]
print(a), print('-'*20)


print(rows[:, np.newaxis])                # shape=(2,1)

# 행의 shape (2,1) x 열의 shape (2,)
#         -> (2,1) x (1,2) -> (2,2) x (2,2)
# 행 [[0,0],[3,3]] x 열 [[0,2],[0,2]]
# [[0,0], [0,2],
#  [3,0], [3,2]]
print(arr[rows[:, np.newaxis], columns])  # shape=(2,2)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------
[ 0 11]
--------------------
[[0]
 [3]]
[[ 0  2]
 [ 9 11]]


In [ ]:
# 고급 인덱싱 (6)

arr = np.arange(15).reshape(3,5)

print(arr), print('-'*20)
print(arr[np.array([0, 2]), 3]) # 브로드캐스팅 [0,2] x [3,3]
# (2,) x 스칼라 -> (2,) x (2,)
# 실제로는 행: [0, 2] // 열: [3, 3]
# 인덱싱: (0,3), (2,3) 위치를 인덱싱

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[ 3 13]


In [ ]:
# 고급 인덱싱 (6)-1

# numpy.newaxis의 사용으로 차원 증가시켜 호환성 확보 후 브로드캐스팅

arr1 = np.array([1, 2, 3, 4, 5]) # (5,) -> (1,5)
arr2 = np.array([11, 12, 13])    # (3,) -> (1,3)
arr1 + arr2


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
# 고급 인덱싱 (6)-2

# numpy.newaxis의 사용으로 차원 증가시켜 호환성 확보 후 브로드캐스팅

arr1= np.array([1, 2, 3, 4, 5]) # (5,)
arr2 = np.array([11, 12, 13])   # (3,)

arr1_nx = arr1[:, np.newaxis]   # (5,1)
arr2_nx = arr2[:, np.newaxis]   # (3,1)
print(f'arr1 shape: {arr1.shape}')
print(f'arr2 shape: {arr2.shape}')
print(f'arr1_nx shape: {arr1_nx.shape}')
print(f'arr2_nx shape: {arr2_nx.shape}')
print('='*30)

print(arr1_nx), print('='*30)
print(arr2_nx), print('='*30)
print(arr1_nx + arr2) # (5,1)x(3,) -> (5,1)x(1,3) -> (5,3)
print('='*30)

print(arr2_nx + arr1) # (3,1)x(5,) -> (3,1)x(1,5) -> (3,5)
print('='*30)

arr1 shape: (5,)
arr2 shape: (3,)
arr1_nx shape: (5, 1)
arr2_nx shape: (3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]
[[11]
 [12]
 [13]]
[[12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]]
[[12 13 14 15 16]
 [13 14 15 16 17]
 [14 15 16 17 18]]


In [ ]:
# 고급 인덱싱 (6)-3

arr1 = np.array([0, 1, 2, 3])
print(arr1.shape)       # shape (4,)

arr1_row = arr1[np.newaxis, :]
arr1_col = arr1[:, np.newaxis]
print(arr1_row.shape)   # shape (1,4)
print(arr1_col.shape)   # shape (4,1)

arr2 = np.array([10, 20, 30])
print(arr2.shape)       # shape (3,)

arr12 = arr1_col + arr2
print(arr12.shape)      # shape (4,3)
print(arr12)

(4,)
(1, 4)
(4, 1)
(3,)
(4, 3)
[[10 20 30]
 [11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 불리언 배열로 인덱싱

arr = np.arange(12).reshape(3,4)
print(arr), print('='*30)

ind = arr > 5
print(ind), print('='*30)

# boolean indexing
print(arr[ind]), print('='*30)

print(ind[:, 1]), print('='*30)

# 2차원 arr 배열의 인덱싱 배열로 처리된 결과는 2차원 배열
print(arr[ind[:, 1]]) # [[ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]
[False False  True]
[[ 8  9 10 11]]


In [ ]:
# 슬라이싱과 인덱스 배열 처리

arr = np.arange(12).reshape(3,4)
print(arr), print('='*30)
print(arr[np.array([1, 2]), 1:3])

ind = arr > 5
print(ind), print('='*30)
print(ind[:, 2]), print('='*30)
print(arr[ind[:, 2], 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[False  True  True]
[[ 5  6]
 [ 9 10]]


In [ ]:
# 인덱스를 반환하는 numpy.nonzero와 numpy.transpose 함수 (1)

arr = np.array([[1, 0, 0],
                [0, 2, 0],
                [1, 1, 0]])
print(arr), print('-'*50)
print(np.nonzero(arr)) # nonzero요소의 (튜플로) 인덱스 반환
print('='*50)

print(arr[np.nonzero(arr)]), print('-'*50)
print(np.nonzero(arr)), print('='*50)
print(np.transpose(np.nonzero(arr)))


[[1 0 0]
 [0 2 0]
 [1 1 0]]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))
[1 2 1 1]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))
[[0 0]
 [1 1]
 [2 0]
 [2 1]]


In [ ]:
# 인덱스를 반환하는 numpy.nonzero와 numpy.transpose 함수 (2)

arr = np.arange(9).reshape(3,3)
print(arr), print('='*30)

print(arr > 3), print('='*30)

# Nonzero함수를 불리언 조건으로 적용하여 True인 색인을 반환
print(np.nonzero(arr > 3)), print('='*30)

# 불리언 배열의 nonzero메소드를 적용 (위 결과와 같음)
print((arr > 3).nonzero())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[False False False]
 [False  True  True]
 [ True  True  True]]
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


In [ ]:
# 인덱스를 반환하는 numpy.nonzero와 numpy.transpose 함수 (3)

# 2, 3차원 배열의 전치
arr = np.arange(4).reshape((2, 2))
print(arr), print('-'*30)
print(np.transpose(arr)), print('='*30)

arr1 = np.ones((1, 2, 3))
print(arr1), print('-'*30)
print(f'arr1 shape: {arr1.shape}'), print('-'*30)

# np.transpose(arr, (arr 행렬을 (a,b,c) 차원으로 전치))
# 기존 arr1은 (면, 행, 열)의 형태 -> (0, 1, 2)라는 순서를 가짐
arr2 = np.transpose(arr1, (1, 0, 2)) # 면과 행을 바꿔라
print(f'arr2 shape: {arr2.shape}')
print(arr2), print('-'*30)

arr3 = np.transpose(arr1, (0, 2, 1)) # 행과 열을 바꿔라
print(f'arr3 shape: {arr3.shape}')
print(arr3), print('-'*30)

# 실제 arr1.T 과 같은 결과를 가짐
arr4 = np.transpose(arr1, (2, 1, 0)) # 면과 열을 바꿔라
print(f'arr4 shape: {arr4.shape}')
print(arr4), print('-'*30)

arr5 = arr1.T
print(f'arr5 shape: {arr5.shape}')
print(arr5)

[[0 1]
 [2 3]]
------------------------------
[[0 2]
 [1 3]]
[[[1. 1. 1.]
  [1. 1. 1.]]]
------------------------------
arr1 shape: (1, 2, 3)
------------------------------
arr2 shape: (2, 1, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
------------------------------
arr3 shape: (1, 3, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]]
------------------------------
arr4 shape: (3, 2, 1)
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]
------------------------------
arr5 shape: (3, 2, 1)
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]


In [ ]:
# 인덱스를 반환하는 numpy.nonzero와 numpy.transpose 함수 (4)

# 1차원 배열은 전치 처리가 되지 않는다?
a = [1, 2, 3]
b = np.array(a) # (3,)

print(b), print('-'*30)
print(b.T), print('-'*30)
print(f'b shape: {b.shape}')
print(f'b.T shape: {b.T.shape}')
print('='*30)

arr = np.array([a]) # np.array([[1,2,3]])
print(arr), print('-'*30)
print(arr.transpose()), print('-'*30)
print(f'arr shape: {arr.shape}')
print(f'arr.T shape: {arr.T.shape}')



[1 2 3]
------------------------------
[1 2 3]
------------------------------
b shape: (3,)
b.T shape: (3,)
[[1 2 3]]
------------------------------
[[1]
 [2]
 [3]]
------------------------------
arr shape: (1, 3)
arr.T shape: (3, 1)


In [ ]:
# 다차원 배열의 전치 1: 면(depth) x 행 x 열

arr1 = np.array([[[0, 1, 2, 3],
                  [4, 5, 6, 7]],
                 [[8, 9, 10, 11],
                  [12, 13, 14, 15]]])

print(arr1)
print(arr1.shape) # (2,2,4)
print('='*30)

# 면과 행을 바꿈
arr2 = np.transpose(arr1, (1, 0, 2))
print(arr2)
print(arr2.shape)
print('='*30)

arr3 = arr1.transpose((1, 0, 2)) # arr2의 결과와 같음
print(arr3)
print(arr3.shape)
print('='*30)

arr4 = arr1.T       # np.transpose(arr1, (2,1,0)) 같음
print(arr1)
print(arr4)
print(arr4.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
(2, 2, 4)
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
(2, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
(4, 2, 2)


In [ ]:
# 다차원 배열의 전치 2: 면(depth) x 행 x 열

# 행렬의 전치는 행과 열을 바꾸기만 하면 되지만,
# 3차원 텐서의 전치는 열 x 행 x 면의 순서로 바뀜

a = np.arange(24).reshape(2,3,4)
print(a)
print(f'shape of a is {a.shape}', '\n', '-'*50)

b = a.T
print(b)
print(f'shape of b is {b.shape}', '\n', '-'*50)

# 아래와 같이 축의 순서를 원하는대로 바꿀 수 있음
c = np.transpose(a, (2,1,0))
print(c)
print(f'shape of c is {c.shape}', '\n', '-'*50)

d = np.transpose(a, (1,0,2))
print(d)
print(f'shape of d is {d.shape}', '\n', '-'*50)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape of a is (2, 3, 4) 
 --------------------------------------------------
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
shape of b is (4, 3, 2) 
 --------------------------------------------------
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
shape of c is (4, 3, 2) 
 --------------------------------------------------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
shape of d is (3, 2, 4) 
 --------------------------------------------------


In [ ]:
# universal function

# 일반 파이썬 for 문 vs 넘파이 벡터화

# 일반 파이썬 : 리스트 a의 원소별 제곱
a = [1, 2, 3, 4]
b = []
for x in a:
    b.append(x ** 2)
print(b)  # [1, 4, 9, 16]


# 넘파이 벡터화
a = np.array([1, 2, 3, 4])
b = a ** 2  # 벡터화된 연산
print(b)    # [1 4 9 16]


[1, 4, 9, 16]
[ 1  4  9 16]


In [ ]:
# class numpy.ufunc

# 유니버셜 함수가 취급하는 입력 / 출력 인수 개수는 다음과 같이 확인
print(f'(이항 연산) np.add.nin : {np.add.nin}')
print(f'(이항 연산) np.add.nout : {np.add.nout}')
print('='*30)

print(f'(단항 연산) np.exp.nin : {np.exp.nin}')
print(f'(단항 연산) np.exp.nout : {np.exp.nout}')


(이항 연산) np.add.nin : 2
(이항 연산) np.add.nout : 1
(단항 연산) np.exp.nin : 1
(단항 연산) np.exp.nout : 1


In [ ]:
# ufunc - reduce() 메소드 (1) : '줄이다' -> 차원을 줄임

print(np.add([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]))
print('-'*20)

arr1 = np.array([1, 2, 3, 4, 5]) # (5,)
print(np.add.reduce(arr1))   # 스칼라 ()
print('-'*20)

arr2 = np.array(([1, 2, 3], [4, 5, 6]))
print(arr2)
print('-'*20)

# 행단위 연산 shape: (2,3) -> (3,)
print(np.add.reduce(arr2)) # default(axis = 0): axis=0에 대해 축 감소 (2,3) -> (3,)
print('-'*20)

# 열단위 연산 shape: (2,3) -> (2,)
print(np.add.reduce(arr2, axis=1)) # axis=1: axis=1에 대해 축 감소 (2,3) -> (2,)
# [[6],
#  [15]] 이렇게 출력이 안나오고, [6,15] 이런식으로 (2,) shape가짐

[ 2  4  6  8 10]
--------------------
15
--------------------
[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]


In [ ]:
# ufunc - reduce() 메소드 (2)

arr3 = np.array([[[1, 2, 3, 4, 5]]])
print(arr3, arr3.shape)     # [[[1 2 3 4 5]]] (1, 1, 5)
print('-'*20)

arr4 = np.add.reduce(arr3)
print(arr4, arr4.shape)     # [[1 2 3 4 5]] (1, 5)
print('-'*20)

arr5 = np.add.reduce(arr4)
print(arr5, arr5.shape)     # [1 2 3 4 5] (5,)
print('-'*20)

arr6 = np.add.reduce(arr5)
print(arr6, arr6.shape)     # 15 shape: ()

[[[1 2 3 4 5]]] (1, 1, 5)
--------------------
[[1 2 3 4 5]] (1, 5)
--------------------
[1 2 3 4 5] (5,)
--------------------
15 ()


In [ ]:
# ufunc - accumulate() 메소드 // 원래 차원이 그대로 유지됨

arr0 = [1, 2, 3, 4, 5]
print(arr0)
print(np.add.accumulate(arr0))
print('-'*20)

print(np.multiply.accumulate(arr0))
print('='*20)

# 2D 행렬
arr = np.arange(12).reshape((3, 4))
print(arr)
print('-'*20)

print(np.add.accumulate(arr)) # axis=0에 대해서
print('-'*20)
print(np.add.accumulate(arr, axis=1)) # 열에대해서 더한 후 축적


[1, 2, 3, 4, 5]
[ 1  3  6 10 15]
--------------------
[  1   2   6  24 120]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
--------------------
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [ ]:
# ufunc - reduceat() 메소드

arr = np.arange(7)
print(arr)

# arr[0:3], arr[3:5], arr[5:6], arr[6:]에
# 해당하는 요소를 각각 더한 값을 반환
print(np.add.reduceat(arr, [0, 3, 5, 6]))
print('='*30)


arr1 = np.linspace(0, 15, 16).reshape(4, 4)
print(arr1)
print('-'*30)

# axis=0 (기본값)이므로, 행 기준으로 연산
# 0:3 -> 0행~2행 // 3:1 -> 빈 범위라서 해당 위치 행(3행) 그대로 사용
# 1:2 -> 1행     // 2:0 -> 빈 범위라서 해당 위치 행(2행) 그대로 사용
# 0: - > 0행~끝
print(np.add.reduceat(arr1, [0, 3, 1, 2, 0]))
print('-'*30)

print(np.add.reduceat(arr1, [0, 3, 1, 2, 0], axis=1))


[0 1 2 3 4 5 6]
[3 7 5 6]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
------------------------------
[[12. 15. 18. 21.]
 [12. 13. 14. 15.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [24. 28. 32. 36.]]
------------------------------
[[ 3.  3.  1.  2.  6.]
 [15.  7.  5.  6. 22.]
 [27. 11.  9. 10. 38.]
 [39. 15. 13. 14. 54.]]


In [ ]:
# ufunc - outer() 메소드

# 배열 A에서 a, 배열 B에서 b를 가지는 모든 쌍인 (a, b)에 ufunc op를 적용

# add.outer
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add.outer(a, b)
print(a.shape, b.shape, c.shape) # (3,) (3,) (3, 3)
print(c)              # [[5 6 7], [6 7 8], [7 8 9]]
print('='*30)

# add.outer
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3, 4])
arr3 = np.add.outer(arr1, arr2)
print(arr1.shape, arr2.shape, arr3.shape) # (2, 3) (4,) (2, 3, 4)
print(arr3)
print('='*30)

# multiply.outer
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3, 4])
arr3 = np.multiply.outer(arr1, arr2)
print(arr1.shape, arr2.shape, arr3.shape) # (2, 3) (4,) (2, 3, 4)
print(arr3)
print('='*30)

# outer (참고만...)
# 입력 배열을 먼저 1차원으로 평탄화 (flatten)한 다음, 외적 연산을 함
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3, 4])
arr4 = np.outer(arr1, arr2)
print(arr1.shape, arr2.shape, arr4.shape) # (2, 3) (4,) (6, 4)
print(arr4)
print('-'*30)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.outer(arr1, arr5)
print(arr1.shape, arr5.shape, arr6.shape) # (2, 3) (2, 2) (6, 4)
print(arr6) # 위의 결과와 같음

(3,) (3,) (3, 3)
[[5 6 7]
 [6 7 8]
 [7 8 9]]
(2, 3) (4,) (2, 3, 4)
[[[ 2  3  4  5]
  [ 3  4  5  6]
  [ 4  5  6  7]]

 [[ 5  6  7  8]
  [ 6  7  8  9]
  [ 7  8  9 10]]]
(2, 3) (4,) (2, 3, 4)
[[[ 1  2  3  4]
  [ 2  4  6  8]
  [ 3  6  9 12]]

 [[ 4  8 12 16]
  [ 5 10 15 20]
  [ 6 12 18 24]]]
(2, 3) (4,) (6, 4)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]]
------------------------------
(2, 3) (2, 2) (6, 4)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]]


In [ ]:
# 유용한 ufunc (1)

# np.subtract
print(np.subtract(1.0, 4.0))
print('='*30)

arr1 = np.arange(9.0).reshape((3, 3))
arr2 = np.arange(3.0)
print(arr1), print('-'*30)
print(arr2), print('-'*30)

print(np.subtract(arr1, arr2))

-3.0
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
------------------------------
[0. 1. 2.]
------------------------------
[[0. 0. 0.]
 [3. 3. 3.]
 [6. 6. 6.]]


In [ ]:
# 유용한 ufunc (2)

# np.power
arr1 = range(6)
a = np.power(arr1, 3)
print(list(arr1)), print('-'*30)
print(a), print('='*30)

arr2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
b = np.power(arr1, arr2)
print(list(arr1)), print('-'*30)
print(arr2), print('-'*30)
print(b), print('='*30)

# 유니버셜 함수에 브로드캐스팅을 적용할 수 있음
arr3 = np.array([[1, 2, 3, 3, 2, 1],
                 [1, 2, 3, 3, 2, 1]])
c = np.power(arr1, arr3)
print(arr3), print('-'*30)
print(c)

[0, 1, 2, 3, 4, 5]
------------------------------
[  0   1   8  27  64 125]
[0, 1, 2, 3, 4, 5]
------------------------------
[1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
------------------------------
[ 0.  1.  8. 27. 16.  5.]
[[1 2 3 3 2 1]
 [1 2 3 3 2 1]]
------------------------------
[[ 0  1  8 27 16  5]
 [ 0  1  8 27 16  5]]


In [ ]:
# 유용한 ufunc (3)

# 삼각 함수

# np.sin, np.cos, np.tan
print(f'np.sin(np.pi/2): {np.sin(np.pi/2)}')
print(f'np.cos(np.pi): {np.cos(np.pi)}')
print('-'*60)

# deg2rad
print(f'np.sin(np.deg2rad(0)): {np.sin(np.deg2rad(0))}')
print(f'np.tan(np.deg2rad(90)): {np.tan(np.deg2rad(90))}')
print('-'*60)

# rad2deg (예상했던 결과는 -1인데...)
print(f'np.cos(np.rad2deg(np.pi)): {np.cos(np.rad2deg(np.pi))}')
print('-'*60)

print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi/180.))

np.sin(np.pi/2): 1.0
np.cos(np.pi): -1.0
------------------------------------------------------------
np.sin(np.deg2rad(0)): 0.0
np.tan(np.deg2rad(90)): 1.633123935319537e+16
------------------------------------------------------------
np.cos(np.rad2deg(np.pi)): -0.5984600690578581
------------------------------------------------------------
[0.         0.5        0.70710678 0.8660254  1.        ]


np.float64(180.0)

In [ ]:
# 유용한 ufunc (4)

# binary 연산

# 13 : 0000 1101
# 17 : 0001 0001
a = np.bitwise_and(13, 17)  # 1
b = np.bitwise_or(13, 17)   # 29
c = np.bitwise_xor(13, 17)  # 28
print(f'a: {a}, b: {b}, c: {c}')
print('-'*20)

# binary_repr (representation)은 10진수를 2진수로 변환
# 비트 수(width)를 지정하지 않으면 가장 짧은 형태로 표현
print(np.binary_repr(17))
print(np.binary_repr(17, width=8))
print('-'*20)

# 14 : 0000 1110
# 3  : 0000 0011
# 13 : 0000 1101
print(np.bitwise_and([14, 3], 13)) # 브로트캐스팅 14 & 13, 3 & 13


a: 1, b: 29, c: 28
--------------------
10001
00010001
--------------------
[12  1]
