### HW2-1

In [10]:
import numpy as np

# 계수 행렬 A와 상수 벡터 b
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
c = np.array([[8, -11, -3]])
b = c.T

# 조건1: np.linalg.solve()로 Ax = b 풀기
x = np.linalg.solve(A, b)
print(f"x = \n{x}")

# 조건2: np.linalg.inv()로 Ax = b 풀기
x2 = np.linalg.inv(A)@b
print(f"x2 = \n{x2}")

# 조건3: 검산
print(f"Ax = \n{np.dot(A, x)}")
print(f"b = \n{b}")


x = 
[[ 2.]
 [ 3.]
 [-1.]]
x2 = 
[[ 2.]
 [ 3.]
 [-1.]]
Ax = 
[[  8.]
 [-11.]
 [ -3.]]
b = 
[[  8]
 [-11]
 [ -3]]


### HW2-2

In [11]:
import numpy as np
import joblib

# 배열 생성
arr1 = np.random.randint(0,10,12).reshape(3, 4)
arr2 = arr1*2

# 조건1 .npy 저장
np.save('arr1.npy', arr1)

# 조건1 .npz 저장
np.savez('arr_combined.npz', a=arr1, b=arr2)

# 조건1 joblib 저장
data = {'arr1': arr1, 'arr2': arr2}
joblib.dump(data, 'arrays.joblib')

# 조건2 로딩
loaded_arr1 = np.load('arr1.npy')
loaded_npz = np.load('arr_combined.npz')
loaded_joblib = joblib.load('arrays.joblib')

# 조건2 출력
print(f"npy: \n{loaded_arr1}"), print('-'*30)
print(f"npz['a']: \n{loaded_npz['a']}"), print('-'*30)
print(f"npz['b']: \n{loaded_npz['b']}"), print('-'*30)
print(f"joblib['arr1']: \n{loaded_joblib['arr1']}"), print('-'*30)
print(f"joblib['arr2']: \n{loaded_joblib['arr2']}")


npy: 
[[3 3 4 6]
 [5 3 2 9]
 [7 7 0 7]]
------------------------------
npz['a']: 
[[3 3 4 6]
 [5 3 2 9]
 [7 7 0 7]]
------------------------------
npz['b']: 
[[ 6  6  8 12]
 [10  6  4 18]
 [14 14  0 14]]
------------------------------
joblib['arr1']: 
[[3 3 4 6]
 [5 3 2 9]
 [7 7 0 7]]
------------------------------
joblib['arr2']: 
[[ 6  6  8 12]
 [10  6  4 18]
 [14 14  0 14]]


### HW2-3

In [16]:
import pandas as pd
import numpy as np

# 조건1. Series 객체 생성
glucose_data = {
    'subject_01': 98,
    'subject_02': 110,
    'subject_03': 87,
    'subject_04': 145,
    'subject_05': 132,
    'subject_06': 120,
}
glucose = pd.Series(glucose_data)
print(f"조건1. 혈당 Series: \n{glucose}"), print('='*50)

# 조건2. 평균 혈당 계산
print(f"조건2. 평균 혈당 수치: {np.mean(glucose)}"), print('='*50)

# 조건3. 혈당 125 이상인 참가자 추출
high_glucose = glucose[glucose >= 125]
print(f"조건3. 혈당이 125 이상인 참가자: \n{high_glucose}"), print('='*50)

# 조건4. 특정 구간 슬라이싱 (라벨 기반, 'subject_05' 포함됨)
sliced = glucose['subject_02':'subject_05']
print(f"조건4. 'subject_02'부터 'subject_05'까지 참가자: \n{sliced}")


조건1. 혈당 Series: 
subject_01     98
subject_02    110
subject_03     87
subject_04    145
subject_05    132
subject_06    120
dtype: int64
조건2. 평균 혈당 수치: 115.33333333333333
조건3. 혈당이 125 이상인 참가자: 
subject_04    145
subject_05    132
dtype: int64
조건4. 'subject_02'부터 'subject_05'까지 참가자: 
subject_02    110
subject_03     87
subject_04    145
subject_05    132
dtype: int64
